# Generated by Django 4.2.5 on 2023-10-27 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("bio", models.TextField(blank=True, max_length=500, null=True)),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        default="uploads/profile_pictures/default.png",
                        upload_to="uploads/profile_pictures",
                    ),
                ),
            ],
        ),
    ]
