# Generated by Django 4.2.6 on 2023-10-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Urutan', models.IntegerField()),
                ('ISBN', models.CharField(max_length=255)),
                ('Judul', models.CharField(max_length=255)),
                ('Penulis', models.CharField(max_length=255)),
                ('Publikasi', models.IntegerField()),
                ('Publisher', models.CharField(max_length=255)),
                ('ImageS', models.CharField(max_length=255)),
                ('ImageM', models.CharField(max_length=255)),
                ('ImageL', models.CharField(max_length=255)),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
