# Generated by Django 4.2.6 on 2023-10-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231026_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Rating',
            new_name='rating',
        ),
    ]
