# Generated by Django 4.2.7 on 2023-12-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rating',
            new_name='Rating',
        ),
    ]
